### ISSUE TITLE
Powered by Google Image

### ISSUE THREAD

**Issue by anandneema14** [ubilabs/geocomplete#214]
Hello,

Can I remove Powered by Google image from the autosuggest list?

If Yes then, How?

-Anand

**Comment by aemkei** [comment]
If you also show a Google Map, it is OK to hide the logo:

https://developers.google.com/places/webservice/policies#logo_requirements

You can hide it using CSS:

```css
.pac-container:after {  /* Disclaimer: not needed to show 'powered by Google' if also a Google Map is shown */
    background-image: none !important;
    height: 0px;
}
```
